version: "3.8"
services:
  open_webui:
    image: ghcr.io/open-webui/open-webui
    ports:
      - "8080:8080"
    volumes:
      - ./open_webui:/app/backend/data
    restart: always
  pull_images:
    image: curlimages/curl
    volumes:
      - .:/opt
    command: "/opt/pull_models.sh"
    depends_on:
      - ollama
  scrape_content:
    image: python:3
    volumes:
      - .:/opt
    command: "/opt/scrape_content.sh"


    
